# Generated by Django 3.1.4 on 2020-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jop_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
